from sqlalchemy import (
    Column, Integer, BigInteger, Text, Date, DateTime, Float, JSON, CHAR, create_engine
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

class Signal(Base):
    __tablename__ = "signals"
    id = Column(Integer, primary_key=True)
    run_date = Column(Date, nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    symbol = Column(Text, nullable=False, index=True)
    last_price = Column(Float)
    current_iv = Column(Float)
    iv_rank_52wk = Column(Float)
    iv_pct_52wk = Column(Float)
    iv_rank_13wk = Column(Float)
    iv_pct_13wk = Column(Float)
    put_call_ratio = Column(Float)
    call_volume = Column(Integer)
    put_volume = Column(Integer)
    opt_volume = Column(Integer)
    av_option_volume = Column(Integer)
    opt_vol_expansion_ratio = Column(Float)
    market_regime = Column(Text)
    is_coiling = Column(Integer)
    dist_to_200dma = Column(Float)
    contraction_mean = Column(Float)
    contraction_median = Column(Float)
    triangle_flag = Column(Integer)
    high_slope = Column(Float)
    low_slope = Column(Float)

    atm_volume_skews = Column(Float)
    atm_dominant_expiry_by_vol = Column(Text)
    atm_dominant_expiry_by_oi = Column(Text)
    atm_oi_depth = Column(Integer)
    atm_oi_skews = Column(Float)
    otm_call_iv_max_skew_expiry = Column(Text)
    otm_call_iv = Column(Float)
    otm_put_iv = Column(Float)
    call_put_iv_skew_pct = Column(Float)
    call_put_iv_skew_pct_avg = Column(Float)
    call_skew_flag = Column(Integer)
    iv_skew_expiries_matched = Column(Integer)
    call_vol_concentration_pct = Column(Float)
    concentration_expiry = Column(Text)
    concentration_strike = Column(Float)
    term_structure_anomaly_expiry = Column(Text)
    term_structure_anomaly_pct = Column(Float)
    term_structure_flag = Column(Integer)
    deal_band_call_vol = Column(Integer)
    deal_band_call_oi = Column(Integer)
    deal_band_vol_oi_ratio = Column(Float)
    deal_band_concentration_pct = Column(Float)
    deal_band_dominant_expiry = Column(Text)
    deal_band_dominant_strike = Column(Float)

    insider_conviction_score = Column(Float)
    cfo_involved = Column(Integer)
    debt_reduction_pct = Column(Float)

    catalyst_flag = Column(Integer)
    catalyst_type = Column(Text)
    catalyst_confidence = Column(Float)
    has_activist_pressure = Column(Integer)

    raw = Column(JSON)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class OptionTick(Base):
    __tablename__ = "option_ticks"
    id = Column(Integer, primary_key=True)
    run_date = Column(Date, nullable=False, index=True)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    symbol = Column(Text, nullable=False, index=True)
    conid = Column(BigInteger, index=True)
    expiry = Column(Text)
    strike = Column(Float)
    right = Column(CHAR(1))
    multiplier = Column(Text)
    trading_class = Column(Text)
    bid = Column(Float)
    ask = Column(Float)
    last = Column(Float)
    implied_vol = Column(Float)
    delta = Column(Float)
    gamma = Column(Float)
    vega = Column(Float)
    theta = Column(Float)
    open_interest = Column(Integer)
    volume = Column(Integer)
    iv_source = Column(Text)
    sample_type = Column(Text)
    src = Column(Text)
    raw = Column(JSON)
    created_at = Column(DateTime(timezone=True), server_default=func.now())